"""Write a Wordle pack from one of the charter's word lists.

    python3 tools/make_wordle_pack.py [--words charter/laws/wordle/words.txt] [--depth 1] [--out packs/wordle/pack.py]

Brief 004's two packs are this generator at two hundred words and two depths, and nothing else
differs between them:

    python3 tools/make_wordle_pack.py --words charter/laws/wordle/words200.txt --depth 1 --out packs/wordle200/d1.py
    python3 tools/make_wordle_pack.py --words charter/laws/wordle/words200.txt --depth 2 --out packs/wordle200/d2.py

Ordinary Python, outside src/: it may import what it likes. What it writes is SURFACE and nothing
else, and every number it writes is in the file, so the repository shows the World whole.

The World it writes is Wordle on those words:
  states        the words, uniform prior
  guesses       every word, `once`, price 1, kernel the game's feedback row by row
  ending        all-green ends the episode, earning 0
  terminal      `claim <word>`: -1 if right, `loss` if wrong
The claims are what make stopping worth something. With "give up" as the only terminal act the
World is degenerate at every depth -- a look ahead values the frontier at V_0, sees a one-in-m hit
and then the loss, and gives up at once (CHARTER E3). That is a fact about the declared World,
not a thing to work around in code, so the World says something else: the agent may claim an
answer, and a wrong claim costs `loss`.
"""
import argparse
import pathlib

WIDTH = 96
# Five guesses and a claim are Wordle's six attempts. A wrong claim must be worse than playing the
# game out and claiming right: five guesses and a claim cost 6, so the loss is one worse.
LOSS = -7
HORIZON = 5
DEPTH = 1
ALL_GREEN = "ggggg"


def feedback(guess, answer):
    """Wordle's rule, duplicate letters included: greens first, then yellows while unmatched
    copies of the letter remain."""
    marks = ["-"] * len(guess)
    unmatched = {}
    for g, a in zip(guess, answer):
        if g != a:
            unmatched[a] = unmatched.get(a, 0) + 1
    for i, (g, a) in enumerate(zip(guess, answer)):
        if g == a:
            marks[i] = "g"
        elif unmatched.get(g, 0) > 0:
            marks[i] = "y"
            unmatched[g] -= 1
    return "".join(marks)


def _lines(pieces, indent):
    pad = " " * indent
    out, line = [], ""
    for i, piece in enumerate(pieces):
        piece = piece + ("," if i < len(pieces) - 1 else "")
        if line and len(line) + 1 + len(piece) > WIDTH:
            out.append(line)
            line = ""
        line = pad + piece if not line else line + " " + piece
    out.append(line)
    return out


def wrapped(cells, indent):
    """A dict literal, written out, wrapped so that every number stays visible."""
    pad = " " * indent
    lines, line = [], ""
    for i, cell in enumerate(cells):
        piece = cell + ("," if i < len(cells) - 1 else "")
        if line and len(line) + 1 + len(piece) > WIDTH:
            lines.append(line)
            line = ""
        line = pad + piece if not line else line + " " + piece
    lines.append(line)
    return "{\n" + "\n".join(lines) + "}"


def cell(key, value):
    return repr(key) + ": " + str(value)


def think_lines(n, a, b, rate, score, fraction="1/2"):
    """CHARTER v0.1 / SURFACE v0.1: the think act. The cost table is the author's fitted model
    ops(s) = a*s^2 + b*s^3/n written cell by cell as arithmetic over two fitted params (K2), so the
    table's source is fitted and it carries its held-out score. Every number here is in the brief."""
    cells = ["cost_a*%d*%d + cost_b*%d*%d*%d/%d" % (s, s, s, s, s, n) for s in range(1, n + 1)]
    return ['# The think act (CHARTER v0.1): one deeper look the one `decide` may buy. f and r are the',
            '# owner\'s; the cost table is the author\'s fit of the kernel\'s own operation counts (brief 005c).',
            'depth_plus(2, source="elicited")',
            'think(fraction=%s, source="elicited")' % fraction,
            'param("cost_a", %s, source="fitted")' % a,
            'param("cost_b", %s, source="fitted")' % b,
            'cost([\n' + "\n".join(_lines(cells, 6)) + '], source="fitted")',
            'rate(%s, source="elicited")' % rate,
            'score(%s, of="cost", source="data")' % score]


def pack(words, depth=DEPTH, listed="charter/laws/wordle/words.txt", think=None):
    n = len(words)
    out = ['# Wordle on the %d words of %s, in that order.' % (n, listed),
           '# Generated by tools/make_wordle_pack.py -- regenerate it, do not edit it by hand.',
           '# Every guess is `once` and costs 1; all-green ends the episode at 0; a claim is right',
           '# for -1 and wrong for `loss`. Five guesses and a claim are Wordle\'s six attempts.',
           'world("wordle", closed=True)',
           'horizon(%d, source="data")' % HORIZON,
           'depth(%d, source="elicited")' % depth,
           'space({"answer": [\n' + "\n".join(_lines([repr(w) for w in words], 6)) + ']})',
           'param("loss", %d, source="elicited")' % LOSS,
           'prior(' + wrapped([cell(w, "1/%d" % n) for w in words], 6) + ', source="data")']

    claims = []
    for guess in words:
        table = wrapped([cell(a, "-1" if a == guess else "loss") for a in words], 8)
        claims.append(repr("claim " + guess) + ": " + table)
    zeros = wrapped([cell(a, "0") for a in words], 12)
    endings = []
    for guess in words:
        endings.append(repr(guess) + ": {" + repr(ALL_GREEN) + ": " + zeros + "}")
    out.append("utility({\n" + ",\n".join(claims) + "},\n        ending={\n"
               + ",\n".join(endings) + "}, source=\"elicited\")")

    out.append('price(' + wrapped([cell(w, "1") for w in words], 6) + ', source="data")')
    for guess in words:
        rows = [repr(a) + ": {" + repr(feedback(guess, a)) + ": 1}" for a in words]
        out.append('act(' + repr(guess) + ', once=True, kernel=table(' + wrapped(rows, 8)
                   + ', source="data"), reads=["answer"])')
    if think:
        out += think_lines(n, *think)
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    root = pathlib.Path(__file__).resolve().parent.parent
    parser.add_argument("--words", default=str(root / "charter" / "laws" / "wordle" / "words.txt"))
    parser.add_argument("--out", default=str(root / "packs" / "wordle" / "pack.py"))
    parser.add_argument("--depth", type=int, default=DEPTH)
    parser.add_argument("--think", metavar="A,B,RATE,SCORE",
                        help="declare the think act: fitted cost params a and b, the rate, the cost's held-out score, comma-separated (b may be negative)")
    args = parser.parse_args()
    words = pathlib.Path(args.words).read_text(encoding="utf-8").split()
    if len(set(words)) != len(words):
        raise SystemExit("the word list repeats a word: the states would not be distinct")
    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    listed = pathlib.Path(args.words)
    try:
        listed = listed.resolve().relative_to(root)
    except ValueError:
        pass
    think = args.think.split(",") if args.think else None
    if think and len(think) != 4:
        raise SystemExit("--think wants four comma-separated numbers: a,b,rate,score")
    out.write_text(pack(words, args.depth, str(listed), think), encoding="utf-8")
    print("wrote " + str(out) + ": " + str(len(words)) + " words, depth " + str(args.depth) + ", "
          + str(len(out.read_text(encoding='utf-8').splitlines())) + " lines")


if __name__ == "__main__":
    main()
